# Generated by Django 5.1 on 2024-09-03 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_customuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
