# Generated by Django 5.1 on 2024-09-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_text_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='text_password',
            field=models.CharField(blank=True, help_text='Provide a password for the user.', max_length=128),
        ),
    ]
