# Generated by Django 5.1 on 2024-09-03 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_text_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='text_password',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
