# Generated by Django 5.1 on 2024-09-07 12:52

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_first_name_remove_student_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_name',
            new_name='father_name',
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default='mother', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.user_profile_image_path),
        ),
    ]
